comment_width = 100
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Module"
match_arm_blocks = false
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
tab_spaces = 4
wrap_comments = true
